### ISSUE TITLE
Test the search on YouTube without pafy

### ISSUE THREAD

**Issue by rnbez** [rafaelbezerra-dev/python-youtube-player#1]
http://www.codeproject.com/Articles/873060/Python-Search-Youtube-for-Video

**Comment by rafaelbezerra-dev** [comment]
the command:
```bash
 $ youtube-dl --skip-download --get-title --get-id --get-duration --max-downlo
ads 10 https://www.youtube.com/results?search_query=work+rihanna
```
Returns the name, the id (that pafy needs) and the video duration (to show the user). The problem is how tho extract this.

**Comment by rnbez** [comment]
The command:

``` bash
 $ youtube-dl --skip-download --get-title --get-id --get-duration --max-downlo
ads 10 https://www.youtube.com/results?search_query=work+rihanna
```

Returns the name, the id (that pafy needs) and the video duration (to show the user). The problem is how to extract this.

**Comment by llaryssa** [comment]
Rafa, can you check this piece of code I wrote right now?

`import subprocess, string

command = "youtube-dl --skip-download --get-title --get-id --get-duration --max-downloads 10 https://www.youtube.com/results?search_query=work+rihanna"
process = subprocess.Popen(command, stdout=subprocess.PIPE ,shell=True)
(output, error) = process.communicate()
output = output.rstrip('\n')

lines = string.split(output, '\n')

names = []
ids = []
times = []

for i in range(0,len(lines),3):
	names.append(lines[i])
	ids.append(lines[i+1])
	times.append(lines[i+2])

for i in range(0,len(names)):
	print "[", i, "] - ", names[i], times[i]

user_response = raw_input('Select your choice: ')

print ids[int(user_response)]`

**Comment by llaryssa** [comment]
Rafa, can you check out this piece of code I wrote right now?
I tested it and it's running fine here. 

```
import subprocess, string

command = "youtube-dl --skip-download --get-title --get-id --get-duration --max-downloads 10 https://www.youtube.com/results?search_query=work+rihanna"
process = subprocess.Popen(command, stdout=subprocess.PIPE ,shell=True)
(output, error) = process.communicate()
output = output.rstrip('\n')

lines = string.split(output, '\n')

names = []
ids = []
times = []

for i in range(0,len(lines),3):
    names.append(lines[i])
    ids.append(lines[i+1])
    times.append(lines[i+2])

for i in range(0,len(names)):
    print "[", i, "] - ", names[i], times[i]

user_response = raw_input('Select your choice: ')

print ids[int(user_response)]
```
